//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eResident_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int BOOKING_ID { get; set; }
        public System.DateTime BOOKING_DATE { get; set; }
        public Nullable<System.TimeSpan> BOOKING_TIME { get; set; }
        public System.DateTime REQ_ON { get; set; }
        public string STATUS { get; set; }
        public string BOOKING_DESC { get; set; }
        public string BOOKING_FEEDBACK { get; set; }
        public string RESIDENT_IC { get; set; }
        public int SERVICE_ID { get; set; }
        public Nullable<int> STAFF_ID { get; set; }
    
        public virtual RESIDENT RESIDENT { get; set; }
        public virtual SERVICE SERVICE { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
