//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eResident_1._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eResidentEntities : DbContext
    {
        public eResidentEntities()
            : base("name=eResidentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOKING> BOOKINGs { get; set; }
        public virtual DbSet<FACILITY> FACILITies { get; set; }
        public virtual DbSet<HOUSE> Houses { get; set; }
        public virtual DbSet<HOUSE_RENT> HOUSE_RENT { get; set; }
        public virtual DbSet<REPORT> REPORTs { get; set; }
        public virtual DbSet<RESIDENT> RESIDENTs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<SERVICE> SERVICEs { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<VISITOR> VISITORs { get; set; }
        public virtual DbSet<View_ResidentBookingList> View_ResidentBookingList { get; set; }
    
        public virtual int PROC_InsertBooking(Nullable<System.DateTime> bOOKING_DATE, Nullable<System.TimeSpan> bOOKING_TIME, string bOOKING_DESC, string rESIDENT_IC, Nullable<int> sERVICE_ID)
        {
            var bOOKING_DATEParameter = bOOKING_DATE.HasValue ?
                new ObjectParameter("BOOKING_DATE", bOOKING_DATE) :
                new ObjectParameter("BOOKING_DATE", typeof(System.DateTime));
    
            var bOOKING_TIMEParameter = bOOKING_TIME.HasValue ?
                new ObjectParameter("BOOKING_TIME", bOOKING_TIME) :
                new ObjectParameter("BOOKING_TIME", typeof(System.TimeSpan));
    
            var bOOKING_DESCParameter = bOOKING_DESC != null ?
                new ObjectParameter("BOOKING_DESC", bOOKING_DESC) :
                new ObjectParameter("BOOKING_DESC", typeof(string));
    
            var rESIDENT_ICParameter = rESIDENT_IC != null ?
                new ObjectParameter("RESIDENT_IC", rESIDENT_IC) :
                new ObjectParameter("RESIDENT_IC", typeof(string));
    
            var sERVICE_IDParameter = sERVICE_ID.HasValue ?
                new ObjectParameter("SERVICE_ID", sERVICE_ID) :
                new ObjectParameter("SERVICE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_InsertBooking", bOOKING_DATEParameter, bOOKING_TIMEParameter, bOOKING_DESCParameter, rESIDENT_ICParameter, sERVICE_IDParameter);
        }
    
        public virtual ObjectResult<Proc_ResidentBookingList_Result> Proc_ResidentBookingList(string rESIDENT_IC)
        {
            var rESIDENT_ICParameter = rESIDENT_IC != null ?
                new ObjectParameter("RESIDENT_IC", rESIDENT_IC) :
                new ObjectParameter("RESIDENT_IC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ResidentBookingList_Result>("Proc_ResidentBookingList", rESIDENT_ICParameter);
        }
    
        public virtual int PROC_InsertReport(string rEPORT_DESC, string rEPORT_TYPE, string rESIDENT_IC)
        {
            var rEPORT_DESCParameter = rEPORT_DESC != null ?
                new ObjectParameter("REPORT_DESC", rEPORT_DESC) :
                new ObjectParameter("REPORT_DESC", typeof(string));
    
            var rEPORT_TYPEParameter = rEPORT_TYPE != null ?
                new ObjectParameter("REPORT_TYPE", rEPORT_TYPE) :
                new ObjectParameter("REPORT_TYPE", typeof(string));
    
            var rESIDENT_ICParameter = rESIDENT_IC != null ?
                new ObjectParameter("RESIDENT_IC", rESIDENT_IC) :
                new ObjectParameter("RESIDENT_IC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_InsertReport", rEPORT_DESCParameter, rEPORT_TYPEParameter, rESIDENT_ICParameter);
        }
    }
}
