//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eResident_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACILITY
    {
        public int FACILITY_ID { get; set; }
        public string FACILITY_NAME { get; set; }
        public string FACILITY_DESCRIPTION { get; set; }
        public byte[] FACILITY_MEDIA { get; set; }
        public int STAFF_ID { get; set; }
    
        public virtual STAFF STAFF { get; set; }
    }
}
