//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eResident_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOUSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOUSE()
        {
            this.HOUSE_RENT = new HashSet<HOUSE_RENT>();
        }
    
        public int HOUSE_ID { get; set; }
        public string HOUSE_BLOCK { get; set; }
        public int HOUSE_LEVEL { get; set; }
        public int HOUSE_NUMBER { get; set; }
        public bool VACANCY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOUSE_RENT> HOUSE_RENT { get; set; }
    }
}
