//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eResident_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOUSE_RENT
    {
        public int RENT_NO { get; set; }
        public System.DateTime START_RENT { get; set; }
        public Nullable<System.DateTime> END_RENT { get; set; }
        public bool STATUS { get; set; }
        public string RESIDENT_IC { get; set; }
        public int HOUSE_ID { get; set; }
    
        public virtual HOUSE HOUSE { get; set; }
        public virtual RESIDENT RESIDENT { get; set; }
    }
}
