//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eResident_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public int REPORT_ID { get; set; }
        public System.DateTime REPORT_DATE { get; set; }
        public string STATUS { get; set; }
        public string REPORT_DESC { get; set; }
        public string REPORT_TYPE { get; set; }
        public string RESIDENT_IC { get; set; }
        public Nullable<int> STAFF_ID { get; set; }
    
        public virtual RESIDENT RESIDENT { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
