//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eResident_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESIDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESIDENT()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
            this.HOUSE_RENT = new HashSet<HOUSE_RENT>();
            this.REPORTs = new HashSet<REPORT>();
            this.VISITORs = new HashSet<VISITOR>();
        }
    
        public string RESIDENT_IC { get; set; }
        public string RESIDENT_NAME { get; set; }
        public string RESIDENT_PHONE { get; set; }
        public string RESIDENT_EMAIL { get; set; }
        public string PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOUSE_RENT> HOUSE_RENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORT> REPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISITOR> VISITORs { get; set; }
    }
}
