//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eResident_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITOR
    {
        public int VISITOR_ID { get; set; }
        public string VISITOR_IC { get; set; }
        public string VISITOR_NAME { get; set; }
        public System.DateTime ARRIVAL_DATE { get; set; }
        public string RESIDENT_IC { get; set; }
        public Nullable<int> STAFF_ID { get; set; }
        public string VISITOR_PHONE { get; set; }
    
        public virtual RESIDENT RESIDENT { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
